changelog:
  categories:
    - title: "🚀 Features"
      labels: [enhancement]
    - title: "🐛 Bug Fixes"
      labels: [bug, fix]
    - title: "⚠️ Breaking Changes"
      labels: [breaking]
    - title: "🔧 Internal"
      labels: [ci, chore, deps]
    - title: "📦 others"
      labels: ["*"]
